### PR TITLE
Fix 'ci' command

### LINKED ISSUE #233: `rome ci` does not run the tests
When running `rome ci`, only the linting is performed.
I think there might be a `process.exit()` call between the `lint` and the `test` command.

## Steps To Reproduce

```bash
$ ./scripts/dev-rome ci
 Building trunk
ℹ Bundling packages/@romejs/cli/bin/rome.ts
✔ Saved to /var/folders/gp/z7cw34td69v0qlsytclcm9600000gn/T/rome-dev
 Executing trunk
⚠ Disk caching has been disabled due to the ROME_CACHE=0 environment variable ⚠

 Running lint

ℹ 1_267 files linted
✔ No known problems!
```

## Expected Results

The tests should be ran.

### PR DESCRIPTION
**Pull request by ooflorent**
Prior this change, `rome ci` was not running the tests.
Closes #233

### CODE REVIEW

File: packages/@romejs/core/master/Master.ts [hunk 1]
```diff
@@ -811,10 +811,7 @@ export default class Master {
     }
   }
 
-  async handleRequestError(
-    req: MasterRequest,
-    rawErr: Error,
-  ): Promise<undefined | Diagnostics> {
+  handleRequestError(req: MasterRequest, rawErr: Error): undefined | Diagnostics {
```
Comment (ooflorent) [inline packages/@romejs/core/master/Master.ts:814]: `DiagnosticsPrinter#print()` is not `async`. After removing unnecessary `await` keywords, the method can be _sync_ again.

File: packages/@romejs/core/master/commands/ci.ts [hunk 2]
```diff
@@ -5,10 +5,31 @@
...
+): Promise<void> {
+  try {
+    await fn();
+    throw new Error('Expected a printer');
+  } catch (err) {
+    if (err instanceof DiagnosticsPrinter) {
+      if (err.hasDiagnostics()) {
+        throw err;
+      } else {
+        req.master.handleRequestError(req, err);
```
Comment (ooflorent) [inline packages/@romejs/core/master/commands/ci.ts:26]: This is kind of dirty. Is this the right approach?

Comment (ooflorent) [reply packages/@romejs/core/master/commands/ci.ts:28]: Maybe the following would be cleaner:
```suggestion
        err.print();
```

File: packages/@romejs/core/master/Master.ts [hunk 3]
```diff
@@ -247,7 +247,7 @@ export default class Master {
       readFile: this.readDiagnosticsPrinterFile.bind(this),
     });
     printer.addDiagnostics(diagnostics);
-    await printer.print();
+    printer.print();
```
Comment (sebmck) [inline packages/@romejs/core/master/Master.ts:250]: Context: This method was previously async and we had another `printSync` method, but I eventually removed it since it was annoying maintaining both and the read file calls aren't that expensive synchronously.

File: packages/@romejs/core/master/commands/ci.ts (hunk 2 above)
Comment (sebmck) [reply packages/@romejs/core/master/commands/ci.ts:28]: That would actually be a noop when there's no diagnostics. There's manual calls to `printer.footer()` which is what prints the "No errors found" message, is that what you meant?

**Comment by sebmck** [comment]
This is great, thank you! I didn't think of wrapping it this way.

File: packages/@romejs/core/master/commands/ci.ts (hunk 2 above)
Comment (ooflorent) [reply packages/@romejs/core/master/commands/ci.ts:28]: Yeah, I called `handleRequestError` to keep the `bridge.alive` test and the `footer` call. The logic could be c/p. Feel free to update the branch to change this.

**Comment by sebmck** [comment]
`rome ci` is failing presumably because `rome test` doesn't actually throw a `DiagnosticPrinter` and instead prints it's own message when there's no diagnostics. Might be best to leave the `throw new Error('Expected a printer');` line out. `rome test` should really just be throwing the `DiagnosticPrinter` anyway and customizing the footer output.

**Comment by sebmck** [comment]
Thank you!
